spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456789
    url: jdbc:mysql://192.168.150.55:3306/zhulin?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  redis:
    host: 127.0.0.1
    port: 6379
  jpa:
    show-sql: true
girl: 18
